apiVersion: v1
kind: Service
metadata:
  name: mssql-db-service
spec:
  ports:
    - port: 1433
  clusterIP: None
  selector:
    app: mssql-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql-db
spec:
  serviceName: "mssql-db-service"
  replicas: 1
  selector:
    matchLabels:
      app: mssql-db
  template:
    metadata:
      labels:
        app: mssql-db
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: "Mahmoud-941-K8s"
          - name: MSSQL_PID
            value: "Developer"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
          - name: mssql-data
            mountPath: /var/opt/mssql
  volumeClaimTemplates:
  - metadata:
      name: mssql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
