apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskmaster-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: taskmaster.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: taskmaster-api-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: taskmaster-webapp-service
            port:
              number: 80
